# Generated by Django 4.2.30 on 2026-06-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('caller_number', models.CharField(max_length=20)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('duration', models.IntegerField(default=0)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
