# Generated by Django 4.2.30 on 2026-06-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('caller_number', models.CharField(max_length=20)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='inbound', max_length=10)),
                ('state', models.CharField(choices=[('INIT', 'Init'), ('LANGUAGE_SELECT', 'Language Selection'), ('MAIN_MENU', 'Main Menu'), ('WEATHER_MENU', 'Weather Menu'), ('MARKET_MENU', 'Market Menu'), ('PEST_MENU', 'Pest Menu'), ('FARMING_TIPS', 'Farming Tips'), ('AI_MENU', 'AI Menu'), ('HANGUP', 'Hangup')], default='INIT', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('sw', 'Kiswahili'), ('lg', 'Luganda'), ('rn', 'Runyankole'), ('ac', 'Acholi')], default='en', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('digits_log', models.TextField(blank=True, help_text='All DTMF digits received, comma-separated')),
            ],
            options={
                'verbose_name': 'Voice Session',
                'verbose_name_plural': 'Voice Sessions',
            },
        ),
    ]
