# Generated by Django 4.2.30 on 2026-06-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLanguagePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('sw', 'Kiswahili'), ('lg', 'Luganda'), ('rn', 'Runyankole')], default='en', max_length=5)),
            ],
            options={
                'verbose_name': 'User Language Preference',
                'verbose_name_plural': 'User Language Preferences',
            },
        ),
    ]
