# Generated by Django 4.2.30 on 2026-06-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0002_userlanguagepreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlanguagepreference',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Kiswahili'), ('lg', 'Luganda'), ('rn', 'Runyankole'), ('ac', 'Acholi')], default='en', max_length=5),
        ),
    ]
